### ISSUE TITLE
$languageId is not an integer

### ISSUE THREAD

**Issue by redpik** [Nosto/nosto-prestashop#259] opened 2018-10-17 15:57 UTC
Hi,

On this line:
https://github.com/Nosto/nosto-prestashop/blob/beta/classes/managers/NostoAdminTabManager.php#L151

... $languageId is not an integer.

Maybe a solution?
`$tab->name[(int)$languageId['id_lang']] = $className;`

Thanx for your help.

**Comment by hannunosto** [comment] 2018-10-18 06:08
Hi @redpik, thanks for reporting this one. Could also let us know on which Prestashop version this error occurs?

**Comment by chenliangde** [comment] 2018-10-19 07:34
@redpik Thank you for reporting it. The cause is that the prestashop Language.getLanguages() has a  "ids_only" parameter introduced started from some of the 1.6 version. We should not use it because the ids_only parameter is not available on  prestashop 1.5 and some of the prestashop 1.6 versions.  I am going to make a fix.

**Comment by redpik** [comment] 2018-10-19 09:30
Hi guys,

Thanx for your answers. It's on a Prestashop 1.6.0.8.

**Comment by chenliangde** [comment] 2018-10-19 10:48
The fix has been released, thanks @redpik

**Closed by chenliangde** 2018-10-19 10:48 UTC
